[package]
name = "kruk_screenshots"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
rdev = {version = "0.5.3", features = ["unstable_grab"]}
screenshots = "0.8.5"
